version: '3.8'
services:
    app:
        image: sofiaapr30/kuis2-sister
        container_name: web-server
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: Admin_admin1
          MYSQL_DATABASE: db_restoran
          MYSQL_USER: admin
          MYSQL_PASSWORD: Admin_admin1
        ports:
            - "9906:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '3060:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
